{{- if .Values.kafka.sasl.enabled }}
{{- if not .Values.kafka.sasl.existingSecretName }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kafka-owl.saslSecretName" . }}
type: Opaque
data:
  username: {{ required "kafka.sasl.username must be set" .Values.kafka.sasl.username | b64enc }}
  password: {{ required "kafka.sasl.password must be set" .Values.kafka.sasl.password | b64enc }}

{{- end }}
{{- end }}
