{{- if .Values.serviceMonitor.create }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: {{ template "kafka-owl.name" . }}
    chart: {{ template "kafka-owl.chart" . }}
    release: {{ if .Values.serviceMonitor.additionalLabels -}}
      {{- .Release.Name -}}
    {{- else -}}
      {{- .Values.serviceMonitor.releaseLabel -}}
    {{- end }}
    heritage: {{ .Release.Service }}
{{- if .Values.serviceMonitor.additionalLabels }}
{{- range $key, $value := .Values.serviceMonitor.additionalLabels }}
    {{ $key }}: {{ $value }}
{{- end }}
{{- end }}
  name: {{ template "kafka-owl.fullname" . }}
spec:
  endpoints:
  - interval: {{ .Values.serviceMonitor.interval }}
    port: http
    path: /metrics
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "kafka-owl.name" . }}
{{- end }}