name: Release Charts

on:
  push:
    branches:
      - master
# on:
#   release:
#     types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Helm Package
        run: |
          helm package ./kowl

      - name: Helm Index
        run: |
          helm repo index . --merge index.yaml

      - name: Commit and push
        run: |
          echo " "
          ls
          echo " "
          cat index.yaml
          echo " "
        # with:
          #repo-token: ${{ secrets.GITHUB_TOKEN }}