name: Release Charts

on:
  push:
    branches:
      - master
# on:
#   release:
#     types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Helm Package
        run: |
          helm package ./kowl

      - name: Helm Index
        run: |
          helm repo index . --merge index.yaml

      - name: Commit and push
        run: |
          git config user.name "GitHub Action ($GITHUB_ACTOR)"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add --all
          git commit -m  '[Auto Commit] New helm chart / helm repo index.yaml'
          git push

